---
- name: Download current Docker Compose
  command: sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Apply executable permissions to the binary
  command: chmod +x /usr/local/bin/docker-compose
